### ISSUE TITLE
[Bug]Emoji Plugin Interferes with HTML Entity Rendering (e.g., &trade;)

### ISSUE THREAD

**Issue by complexusprada** [Milkdown/milkdown#1834]
### Initial checklist

- [x] I agree to follow the [code of conduct](https://github.com/Saul-Mirone/milkdown/blob/main/CODE_OF_CONDUCT.md)
- [x] I searched [issues](hhttps://github.com/Saul-Mirone/milkdown/issues) and [discussions](https://github.com/Saul-Mirone/milkdown/discussions) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

    "@milkdown/crepe": "^7.6.4",     "@milkdown/plugin-emoji": "^7.7.0",

#### Description  
When the emoji plugin is enabled, HTML entities (e.g., `&trade;`, `&copy;`) are not rendered correctly. Instead:  
- **Milkdown crashes** or fails to process the input.  

#### Steps to Reproduce  
1. Enable the emoji plugin:  
   ```ts  
   editor.use(emoji);  

### Expected behavior

HTML entities should render as symbols (™, ©, etc.) regardless of the emoji plugin’s presence.  

### Actual behavior

The emoji plugin disrupts standard HTML entity parsing, leading to crashes or unprocessed text.

### Runtime

Chrome

### OS

Linux

### Build and bundle tools

Vite

**Comment by Saul-Mirone** [comment]
Fixed in v7.9.1.

**Comment by complexusprada** [comment]
The bug persists in  "@milkdown/plugin-emoji": "^7.10.4",

**Comment by knownasilya** [comment]
@complexusprada did you get this working?

**Comment by knownasilya** [comment]
@Saul-Mirone this is still an issue with 7.13. Looks like characters like © are parsed as emoji, and when they go through the plugin the dom result is undefined, which makes sense

<img width="634" alt="Image" src="https://github.com/user-attachments/assets/34d06d1a-cda9-4285-ba24-8a1d1e98ffca" />

Node looks like so:
```json
{
  "type": "emoji",
  "attrs": {
    "html": "©"
  },
  "marks": [
    {
      "type": "strong",
      "attrs": {
        "marker": "*"
      }
    }
  ]
}
```

And later it errors here (prosemirror-model/dist/index.js):

<img width="634" alt="Image" src="https://github.com/user-attachments/assets/a0c9bc31-2981-4ca3-be32-b4f7aaf51d64" />
